Участник: Куляскин М.О. 

Направление: DS

**В данном кейсе передо мной была поставлена задача: из имеющихся данных посчитать, как каждая акция, во время ее проведения, повлияла на объем приобретенных напитков. В решении я использовал библиотеку для анализа данных pandas.** 
1.	**Исследовательский анализ.** Перед тем, как начинать решать задачу, я загрузил все таблицы в Jupyter-Notebook и просмотрел описание их полей в ТЗ. Каждая акция из таблицы promo проводилась в определенный промежуток времени. В таблице effect есть данные о дополнительных литрах (то есть о том, что нам нужно в конечном счете найти) на каждый день и напиток в соответствующем городе. В таблице drinks есть информация о принадлежности каждого продукта к алкогольным или безалкогольным. Это поможет нам при сопоставлении акций и эффекта от них. Остальные таблицы я не использовал, т.к. они не предоставляют информации об акциях или их связи с эффектом. При анализе используемых таблиц я исправил некоторые недоработки в данных: проверил типы колонок и переопределил нужные, заменил или удалил пропущенные значения, добавил необходимые дополнительные строки.
2.	**Решение задачи.** Все мое решение заключается в том, чтобы сопоставить каждой акции суммарный эффект от нее. Для этого я написал несколько функций, считывающих данные о наличии акции в том или ином городе, типе продукта (алкогольный или безалкогольный) на который действует предложение и перечень всех дат проведения акции. Далее для каждой акции я нахожу дополнительный эффект и добавляю его в таблицу promo. 
3.	**Итоги.** Мы получили таблицу promo с дополнительным полем volume_litr, которое показывает, сколько дополнительных литров принесла каждая акция в период ее проведения. По полученным данным мы могли бы оценить зависимость затрат на акцию и объема бонусных продаж, которые она дала.

## Исследовательский анализ данных

In [1]:
#Импорт всех необходимых библиотек
import pandas as pd
import datetime

In [3]:
!pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\1\appdata\local\programs\python\python310\lib\site-packages (10.0.0)

WARNING: You are using pip version 21.2.3; however, version 22.3.1 is available.
You should consider upgrading via the 'C:\Users\1\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

Requirement already satisfied: numpy>=1.16.6 in c:\users\1\appdata\local\programs\python\python310\lib\site-packages (from pyarrow) (1.22.2)

In [2]:
#Указание пути до всех parquet файлов в локальной директории 
attack_probability_file = r'attack_probability.parquet'
daily_volume_file = r'daily_volume.parquet'
drinks_file = r'drinks.parquet'
effect_file = r'effect.parquet'
promo_file = r'promo.parquet'
sales_file = r'sales.parquet'

In [4]:
#Чтение всех данных в DataFrame
attack_probability = pd.read_parquet(attack_probability_file, engine='auto')
daily_volume = pd.read_parquet(daily_volume_file, engine='auto')
drinks = pd.read_parquet(drinks_file, engine='auto')
effect = pd.read_parquet(effect_file, engine='auto')
promo = pd.read_parquet(promo_file, engine='auto')
sales = pd.read_parquet(sales_file, engine='auto')

In [5]:
#Размеры всех таблиц
print(attack_probability.shape)
print(daily_volume.shape)
print(drinks.shape)
print(effect.shape)
print(promo.shape)
print(sales.shape)

(3685, 4)
(3778274, 5)
(11, 2)
(48942, 4)
(65, 17)
(32164, 5)

In [6]:
attack_probability.sample(5)

      Unnamed: 0      city        date  attack probability
3500        3500     Салем  1996-07-22            0.123116
723          723    Лондон  1996-04-16            0.731156
218          218  Коукворт  1996-09-28            0.060302
2536        2536    Кромер  1996-09-01            0.110553
3104        3104  Даффтаун  1996-05-22            0.256281

In [7]:
daily_volume.sample(5)

                  city       id         product        date  volume_litr
2811838          Париж  3740961  Сливочное пиво  1997-02-03    28.205720
1932048       Даффтаун  5661608   Чешуя дракона  1996-11-03    16.278074
2067225  Литтл Уингинг  4811595   Чешуя дракона  1997-11-21    16.613511
2676066         Авимор  9895602  Огненный виски  1997-09-15     1.682804
3395280       Коукворт  9348971  Огненный виски  1997-06-04     6.657298

In [8]:
sales.sample(5)

,date,drink,city,segment,volume_litr
13449,1996-11-01,Безалкогольные,Нью-Йорк,Пожиратели смерти,13.309307
6083,1996-05-18,Безалкогольные,Литтл Уингинг,Орден Феникса,12.988600
21928,1997-05-13,Алкогольные,Лондон,Пожиратели смерти,8.024050
3818,1996-03-27,Алкогольные,Салем,Орден Феникса,248.091030
29898,1997-11-10,Алкогольные,Лондон,Пожиратели смерти,11.536650

In [9]:
drinks.sample(5)

                  Напиток             Тип
5           Тыквенный сок  Безалкогольный
2  Шипучий персиковый чай  Безалкогольный
9                    Вода  Безалкогольный
6          Огненный виски     Алкогольный
7            Настой тыквы  Безалкогольный

In [10]:
effect.sample(5)

             date           product      city  volume_litr
10724  1996-09-04    Сливочное пиво  Коукворт     0.000019
28995  1997-02-19    Огненный виски  Нью-Йорк     0.000492
48189  1997-08-28  Смородиновый ром   Абердин     0.000240
41629  1997-03-17    Огненный виски     Париж     0.000149
1221   1996-12-26  Смородиновый ром    Кромер     0.000005

In [11]:
promo.sample(5)

,Название,Начало,Конец,Кромер,Париж,Бат,Лондон,Салем,Коукворт,Авимор,Даффтаун,Абердин,Нью-Йорк,Литтл Уингинг,Алкогольное,Безалкогольное,"Затраты на акцию, галлеонов"
57,Настоящий мародер,1996-03-05,1996-05-24,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN
44,С литрушки на лягушку,1997-04-01,1997-04-30,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,NaN
39,С литрушки на лягушку + Карликовые пушистики,1996-11-01,1996-11-30,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,NaN
18,Партнер заведений магазин Ханидьюкс,1997-01-15,1997-05-31,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0
41,С литрушки на лягушку,1997-01-01,1997-01-31,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,NaN

После анализа полей из всех таблиц я понял, что для нахождения эффекта с акции понадобятся только таблицы effect, promo и drinks. Результирующая таблица будет содержать в себе все данные таблицы Promo и дополнительный столбец с подсчитанным эффектом на каждую акцию volume_litr(свой для одной и той же акции за разные интервалы ее проведения).
Проведем анализ данных из этих таблиц.

In [12]:
#Проверяем типы столбцов таблицы promo
promo.dtypes

Название                        object
Начало                          object
Конец                           object
Кромер                         float64
Париж                          float64
Бат                            float64
Лондон                         float64
Салем                          float64
Коукворт                       float64
Авимор                         float64
Даффтаун                       float64
Абердин                        float64
Нью-Йорк                       float64
Литтл Уингинг                  float64
Алкогольное                    float64
Безалкогольное                 float64
Затраты на акцию, галлеонов    float64
dtype: object

In [13]:
type(promo['Конец'][0])

str

Колонки 'Начало' и 'Конец' имеют тип string. Для того, чтобы получить список всех промежуточных дат из каждого интервала проведения акции переведем это поле в datetime.

In [14]:
promo['Начало'] = promo['Начало'].apply(lambda x: datetime.datetime.strptime(x,"%Y-%m-%d").date())

In [15]:
promo['Конец'] = promo['Конец'].apply(lambda x: datetime.datetime.strptime(x,"%Y-%m-%d").date())

In [16]:
type(promo['Начало'][0])

datetime.date

Проверим наши данные на пропущенные значения.

In [17]:
promo.isna().sum()

Название                        4
Начало                          0
Конец                           0
Кромер                          0
Париж                           0
Бат                             0
Лондон                          0
Салем                           0
Коукворт                        0
Авимор                          0
Даффтаун                        0
Абердин                         0
Нью-Йорк                        0
Литтл Уингинг                   0
Алкогольное                     0
Безалкогольное                  0
Затраты на акцию, галлеонов    36
dtype: int64

В таблице promo есть 4 акции без названия. Дадим им названия сами.

In [18]:
promo[promo['Название'].isna() == True]

,Название,Начало,Конец,Кромер,Париж,Бат,Лондон,Салем,Коукворт,Авимор,Даффтаун,Абердин,Нью-Йорк,Литтл Уингинг,Алкогольное,Безалкогольное,"Затраты на акцию, галлеонов"
3,None,1996-01-01,1996-02-29,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1292.139684
15,None,1996-10-01,1997-01-31,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,43241.642188
24,None,1996-01-13,1996-01-26,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,NaN
26,None,1996-02-07,1996-02-21,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,NaN

In [19]:
promo.loc[3,'Название'] = 'Безымянная акция №1'
promo.loc[15,'Название'] = 'Безымянная акция №2'
promo.loc[24,'Название'] = 'Безымянная акция №3'
promo.loc[26,'Название'] = 'Безымянная акция №4'

Исследуем таблицу drinks

In [20]:
drinks.isna().sum()

Напиток    0
Тип        0
dtype: int64

В таблице effect в дальнейшем решении кейса будет продукт под названием 'Безалкогольное'. Добавим в таблицу drinks напиток Безалкогольное с типом 'Безалкогольный'.

In [21]:
drinks.loc[len(drinks.index)] = ['Безалкогольное', 'Безалкогольный']

Пропущенных значений нет, значит можем идти дальше. Таблица effect:

In [22]:
effect.isna().sum()

date              0
product           0
city           3804
volume_litr       0
dtype: int64

В таблице effect 3804 пропущенных городов, в которых проводилась акция.

In [23]:
effect[effect['city'].isna() == True]

             date           product  city  volume_litr
65     1996-02-10    Безалкогольное  None          0.0
108    1996-12-30     Чешуя дракона  None          0.0
112    1996-08-14              Вода  None          0.0
145    1997-01-03    Сливочное пиво  None          0.0
147    1996-10-04              Вода  None          0.0
...           ...               ...   ...          ...
48879  1997-07-23    Огненный виски  None          0.0
48889  1997-07-24     Чешуя дракона  None          0.0
48897  1997-07-23    Сливочное пиво  None          0.0
48915  1997-07-21     Чешуя дракона  None          0.0
48939  1997-07-24  Смородиновый ром  None          0.0

[3804 rows x 4 columns]

Проверим, есть ли значимые поля volume_litr в таких строках.

In [24]:
effect[effect['city'].isna() == True]['volume_litr'].unique()

array([0.])

Значимых полей нет, а значит мы можем удалить все такие строки из таблицы effect.

In [25]:
effect.drop(list(effect[effect['city'].isna() == True].index),inplace=True)

In [26]:
type(effect['date'][0])

str

В таблице effect так же поля с датой типа string. Заменим их на datetime

In [27]:
effect['date'] = effect['date'].apply(lambda x: datetime.datetime.strptime(x,"%Y-%m-%d").date())

In [28]:
type(effect['date'][0])

datetime.date

## Решение задачи
Теперь перейдем к выполнению зачачи. Нам необходимо по каждой акции из таблицы promo подсчитать дополнительный эффект в литрах. Для этого я напишу функции, которые будут извлекать из таблицы promo список дат, в которые проводилась акция, список с городами, в которых эта акция проводится и два флага на алкогольные и безалкогольные напитки. Затем для каждой акции я буду проверять соответствие дате, города и продукта в таблице effect и если все будет удовлетворять, то буду прибавлять параметр volume_litr к суммарному эффекту этой акции.

1)Проверим количество повторяющихся акций.

In [29]:
promo.groupby('Название').count()

,Начало,Конец,Кромер,Париж,Бат,Лондон,Салем,Коукворт,Авимор,Даффтаун,Абердин,Нью-Йорк,Литтл Уингинг,Алкогольное,Безалкогольное,"Затраты на акцию, галлеонов"
Название,,,,,,,,,,,,,,,,
"""Все и сразу"" набор",1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
"""Министерство магии"" только на алкоголь",1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
(Орден Феникса),2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0
Back to Hogwarts,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Скидка на Сливочное пиво 2 кната если на бармена сработали чары,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Акция при поимке Пикси от 15 литров напитков,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Безымянная акция №1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Безымянная акция №2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Безымянная акция №3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Безымянная акция №4,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Библиотеки Куокворта купоны на скидку,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Библиотеки Куокворта читательский скидка,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Выпить на удачу,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
"Газета ""Придира""",1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
"Газета ""Придира"" -2 кната не более 25 литров",1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
"Гринготс разный пол (без чар, трансфигурации и оборотного зелья)",1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Двойная сладость,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Квоффл в кольцо,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Клинок за пророк,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Конфетки за метки,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Лавка Оливандера октябрь,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
"Лучше золотой снитч в руках, чем гиппогриф в небе",1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
"Магазин ""Зонко"" Двойная сладость",1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
МетлаПлюс,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Минус 6 кнатов за безалкогольные напитки,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Минус кнат алкогольное,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Минус кнат на Чешую Дракона если бармен под чарами,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Напиток и омолаживающее зелье,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Настоящий мародер,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Обмен любезностями,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
ПРА СУПЕР ГАЛЕОН,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
"Партнер ""Чайный пакетик Розы ли""",1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Партнер заведений магазин Ханидьюкс,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Партнер заведений магазин Ханидьюкс 1997,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
"Подписка на ""Ежедневный пророк"" + скидка от 15 литров напитка",1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Преданный фанат спорта,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
С литрушки на лягушку,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,0
С литрушки на лягушку + Карликовые пушистики,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,3
С литрушки на лягушку 12 литров,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
С литрушки на лягушку 16 литров,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
С литрушки на лягушку скидка на безалкогольные напитки если взял 15 литров алкоголя,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Скидка на Огненный виски 3 кната если на бармена сработали чары,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Сладкий бизнес декабрь 1997,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Сладкий бизнес и лягушка + 15 литров напитков,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Сладкий бизнес ноябрь 1997,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Сладкий бизнес при покупке от 15 литров в любом заведении,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Турнир трех волшебников за метлы,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Флориш и Блоттс июнь,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Флориш и Блоттс май,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0

Для удобства я переименую одинаковые акции.

In [30]:
promo[promo['Название'] == '(Орден Феникса)']

,Название,Начало,Конец,Кромер,Париж,Бат,Лондон,Салем,Коукворт,Авимор,Даффтаун,Абердин,Нью-Йорк,Литтл Уингинг,Алкогольное,Безалкогольное,"Затраты на акцию, галлеонов"
10,(Орден Феникса),1997-08-02,1997-08-31,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,NaN
11,(Орден Феникса),1997-09-01,1997-12-31,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN

In [31]:
promo.loc[10,'Название'] = '(Орден Феникса)_1'
promo.loc[11,'Название'] = '(Орден Феникса)_2'

In [32]:
promo[promo['Название'] == 'С литрушки на лягушку']

,Название,Начало,Конец,Кромер,Париж,Бат,Лондон,Салем,Коукворт,Авимор,Даффтаун,Абердин,Нью-Йорк,Литтл Уингинг,Алкогольное,Безалкогольное,"Затраты на акцию, галлеонов"
41,С литрушки на лягушку,1997-01-01,1997-01-31,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,NaN
42,С литрушки на лягушку,1997-02-01,1997-02-28,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN
43,С литрушки на лягушку,1997-03-01,1997-03-31,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN
44,С литрушки на лягушку,1997-04-01,1997-04-30,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,NaN
45,С литрушки на лягушку,1997-05-01,1997-05-31,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,NaN
46,С литрушки на лягушку,1997-06-01,1997-06-30,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,NaN
47,С литрушки на лягушку,1997-07-01,1997-07-31,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN
48,С литрушки на лягушку,1997-08-01,1997-08-31,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,NaN
49,С литрушки на лягушку,1997-09-01,1997-09-30,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,NaN
50,С литрушки на лягушку,1997-10-01,1997-10-31,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,NaN
52,С литрушки на лягушку,1997-11-01,1997-11-30,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,NaN
53,С литрушки на лягушку,1997-12-01,1997-12-31,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,NaN

In [33]:
promo.loc[41,'Название'] = 'С литрушки на лягушку_1'
promo.loc[42,'Название'] = 'С литрушки на лягушку_2'
promo.loc[43,'Название'] = 'С литрушки на лягушку_3'
promo.loc[44,'Название'] = 'С литрушки на лягушку_4'
promo.loc[45,'Название'] = 'С литрушки на лягушку_5'
promo.loc[46,'Название'] = 'С литрушки на лягушку_6'
promo.loc[47,'Название'] = 'С литрушки на лягушку_7'
promo.loc[48,'Название'] = 'С литрушки на лягушку_8'
promo.loc[49,'Название'] = 'С литрушки на лягушку_9'
promo.loc[50,'Название'] = 'С литрушки на лягушку_10'
promo.loc[52,'Название'] = 'С литрушки на лягушку_11'
promo.loc[53,'Название'] = 'С литрушки на лягушку_12'

In [34]:
promo[promo['Название'] == 'С литрушки на лягушку + Карликовые пушистики']

,Название,Начало,Конец,Кромер,Париж,Бат,Лондон,Салем,Коукворт,Авимор,Даффтаун,Абердин,Нью-Йорк,Литтл Уингинг,Алкогольное,Безалкогольное,"Затраты на акцию, галлеонов"
32,С литрушки на лягушку + Карликовые пушистики,1996-06-01,1996-07-14,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,51.328365
34,С литрушки на лягушку + Карликовые пушистики,1996-09-15,1996-09-30,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,150.140247
37,С литрушки на лягушку + Карликовые пушистики,1996-10-01,1996-10-31,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,310.590123
39,С литрушки на лягушку + Карликовые пушистики,1996-11-01,1996-11-30,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,NaN
40,С литрушки на лягушку + Карликовые пушистики,1996-12-01,1996-12-31,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,NaN

In [35]:
promo.loc[32,'Название'] = 'С литрушки на лягушку + Карликовые пушистики_1'
promo.loc[34,'Название'] = 'С литрушки на лягушку + Карликовые пушистики_2'
promo.loc[37,'Название'] = 'С литрушки на лягушку + Карликовые пушистики_3'
promo.loc[39,'Название'] = 'С литрушки на лягушку + Карликовые пушистики_4'
promo.loc[40,'Название'] = 'С литрушки на лягушку + Карликовые пушистики_5'

In [36]:
promo.groupby('Название').count()

,Начало,Конец,Кромер,Париж,Бат,Лондон,Салем,Коукворт,Авимор,Даффтаун,Абердин,Нью-Йорк,Литтл Уингинг,Алкогольное,Безалкогольное,"Затраты на акцию, галлеонов"
Название,,,,,,,,,,,,,,,,
"""Все и сразу"" набор",1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
"""Министерство магии"" только на алкоголь",1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
(Орден Феникса)_1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
(Орден Феникса)_2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Back to Hogwarts,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Сладкий бизнес ноябрь 1997,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Сладкий бизнес при покупке от 15 литров в любом заведении,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Турнир трех волшебников за метлы,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Флориш и Блоттс июнь,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Флориш и Блоттс май,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0

2)Произведем join таблиц effect и drinks по полю 'product' для того, чтобы проверять тип напитка при учете его в акциях.

In [37]:
#Переименуем поле 'Напиток' в таблице drinks на поле 'product'
drinks.rename(columns={'Напиток':'product'}, inplace=True)

In [38]:
effect = effect.merge(drinks, on='product', how='left')

3)Напишем функцию select_arr_dates, котрая будет забирать список дат проведения акции из таблицы promo.

In [39]:
def select_arr_dates(promo_name):
    d1 = promo[promo['Название'] == promo_name]['Начало'].values[0]
    d2 = promo[promo['Название'] == promo_name]['Конец'].values[0]
    days = [d1 + datetime.timedelta(days=x) for x in range((d2-d1).days + 1)]
    return days

4)Напишем функцию select_city, которая будет возвращать список городов где проводится акция.

In [40]:
def select_city(promo_name):
    cities_list = list(promo[promo['Название'] == promo_name].columns[3:14])
    values_list = list(promo[promo['Название'] == promo_name].values[0][3:14])
    list_cities = []
    for index in range(len(cities_list)):
        if values_list[index] == 1.0:
            list_cities.append(cities_list[index])
    return list_cities

5)Напишем функцию select_alc, которая будет возвращать кортеж с двумя параметрами (Алкогольный или None, Безалкогольный или None)

In [41]:
def select_alc(promo_name):
    alc_flag = promo[promo['Название'] == promo_name]['Алкогольное'].values[0]
    non_alc_flag = promo[promo['Название'] == promo_name]['Безалкогольное'].values[0]
    alc_non_alc = ('Алкогольный' if alc_flag == 1.0 else None, 'Безалкогольный' if non_alc_flag == 1.0 else None)
    return alc_non_alc

6)Напишем функцию result_litr, которая будет для каждой акции подсчитывать все дополнительные литры из таблицы effect.

In [42]:
def result_litr(promo_name):
    arr_dates = select_arr_dates(promo_name)
    list_cities = select_city(promo_name)
    alc_non_alc = select_alc(promo_name)
    sum_volume_litr = 0
    for date in arr_dates: #проходимся циклом по всем дням проведения акции
        sum_volume_litr += effect[ (effect['date'] == date)  #срезаем серию по условиям даты, типа напитка и 
                              & (effect['Тип'] == alc_non_alc[0]) | (effect['Тип'] == alc_non_alc[1]) # наличия в городе
                              & (effect['city'].isin(list_cities)) ]['volume_litr'].sum() #суммируем все доп. литры
    return sum_volume_litr

Теперь пройдемся циклом по всем акциям из таблицы promo и результаты исполнения функции result_litr будем добавлять в список

In [49]:
result_bonus_litr = []
for index in range(len(promo)):
    result_bonus_litr.append(result_litr(promo['Название'].loc[index]))

In [50]:
result_bonus_litr

[1400236.8203395393,
 1098720.479687092,
 129.30975375673034,
 2369402.1988681755,
 579625.8211454846,
 1027258.5003883133,
 1990487.2151043036,
 571940.1855327816,
 2614616.8720906223,
 0,
 0.0,
 4927063.203936629,
 1120902.2712801155,
 1220758.296317103,
 2458542.479047294,
 5573010.883693287,
 258.2189450745971,
 6783385.581550253,
 25177.366047364587,
 698930.9984283674,
 577575.0188462388,
 6766148.126755496,
 2082706.5775307654,
 1932594.336394679,
 377454.8282422127,
 566190.7707310984,
 527031.4804528928,
 661845.58528751,
 0.031989914946432725,
 0.0,
 2579536.60838762,
 3400154.0083351433,
 1837842.929600911,
 2480363.738820235,
 542059.2842312448,
 362468.487984936,
 1098843.133042633,
 1044522.0843226749,
 1078331.3068056323,
 1184916.488718166,
 838768.3734781725,
 0.008603504311427172,
 872575.5017355947,
 1406607.5331779153,
 813179.434794577,
 1098620.841652075,
 1171140.486633005,
 1176502.5953954512,
 1190645.4359135677,
 30213.27267634819,
 901074.4739516298,
 947641.1351866564,
 1171596.7326630442,
 1403375.3945562853,
 656398.9750348136,
 1815798.1653475321,
 1874781.926270228,
 3576157.926803619,
 635132.4041435763,
 508048.0272342674,
 1296202.516066372,
 7.645439787844441,
 864676.8532230454,
 1181849.7560679324,
 1364939.006296264]

In [51]:
promo['volume_litr'] = result_bonus_litr

In [52]:
promo

,Название,Начало,Конец,Кромер,Париж,Бат,Лондон,Салем,Коукворт,Авимор,Даффтаун,Абердин,Нью-Йорк,Литтл Уингинг,Алкогольное,Безалкогольное,"Затраты на акцию, галлеонов",volume_litr
0,Турнир трех волшебников за метлы,1996-03-02,1996-04-05,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.821500e+04,1.400237e+06
1,Клинок за пророк,1997-03-09,1997-04-18,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,6.091402e+04,1.098720e+06
2,Квоффл в кольцо,1997-06-11,1997-07-25,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,5.639899e+01,1.293098e+02
3,Безымянная акция №1,1996-01-01,1996-02-29,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.292140e+03,2.369402e+06
4,Конфетки за метки,1996-04-04,1996-04-30,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,3.695881e+04,5.796258e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,Back to Hogwarts,1996-08-07,1996-09-05,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,1.296203e+06
61,"Газета ""Придира""",1996-09-01,1996-10-07,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,NaN,7.645440e+00
62,Лавка Оливандера октябрь,1996-10-13,1996-10-31,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,8.646769e+05
63,Акция при поимке Пикси от 15 литров напитков,1996-12-21,1997-01-21,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,NaN,1.181850e+06
64,"Газета ""Придира"" -2 кната не более 25 литров",1997-08-24,1997-09-27,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.338751e-15,1.364939e+06

## Итог
Мы получили таблицу promo с дополнительным полем volume_litr, которое показывает, сколько дополнительных литров принесла каждая акция в период ее проведения.